export type PlayerStat = {
  rank: number;
  player: string;
  chineseName: string;
  team: string;
  teamCode: string;
  value: number;
  matches: number;
};

export const goalsRanking: PlayerStat[] = [
  { rank: 1, player: "Lionel Messi", chineseName: "莱昂内尔·梅西", team: "阿根廷", teamCode: "ARG", value: 5, matches: 2 },
  { rank: 2, player: "Kylian Mbappe", chineseName: "基利安·姆巴佩", team: "法国", teamCode: "FRA", value: 4, matches: 2 },
  { rank: 3, player: "Erling Haaland", chineseName: "埃尔林·哈兰德", team: "挪威", teamCode: "NOR", value: 4, matches: 2 },
  { rank: 4, player: "Vinicius Junior", chineseName: "维尼修斯·儒尼奥尔", team: "巴西", teamCode: "BRA", value: 4, matches: 3 },
  { rank: 5, player: "Jonathan David", chineseName: "乔纳森·戴维", team: "加拿大", teamCode: "CAN", value: 3, matches: 2 },
  { rank: 6, player: "Deniz Undav", chineseName: "德尼兹·翁达夫", team: "德国", teamCode: "GER", value: 3, matches: 2 },
  { rank: 7, player: "Ismael Saibari", chineseName: "伊斯梅尔·塞巴里", team: "摩洛哥", teamCode: "MAR", value: 3, matches: 3 },
  { rank: 8, player: "Matheus Cunha", chineseName: "马特乌斯·库尼亚", team: "巴西", teamCode: "BRA", value: 3, matches: 3 },
  { rank: 9, player: "Johan Manzambi", chineseName: "约翰·曼赞比", team: "瑞士", teamCode: "SUI", value: 3, matches: 3 },
  { rank: 10, player: "Brian Brobbey", chineseName: "布赖恩·布罗贝伊", team: "荷兰", teamCode: "NED", value: 3, matches: 3 },
  { rank: 11, player: "Ousmane Dembélé", chineseName: "Dembélé", team: "法国", teamCode: "FRA", value: 3, matches: 3 },
  { rank: 12, player: "Folarin Balogun", chineseName: "福拉林·巴洛贡", team: "美国", teamCode: "USA", value: 2, matches: 2 },
  { rank: 13, player: "Kai Havertz", chineseName: "凯·哈弗茨", team: "德国", teamCode: "GER", value: 2, matches: 2 },
  { rank: 14, player: "Yasin Ayari", chineseName: "亚辛·阿亚里", team: "瑞典", teamCode: "SWE", value: 2, matches: 2 },
  { rank: 15, player: "Eli Just", chineseName: "伊莱·贾斯特", team: "新西兰", teamCode: "NZL", value: 2, matches: 1 },
  { rank: 16, player: "Cyle Larin", chineseName: "赛尔·拉林", team: "加拿大", teamCode: "CAN", value: 2, matches: 2 },
  { rank: 17, player: "Crysencio Summerville", chineseName: "克里森西奥·萨默维尔", team: "荷兰", teamCode: "NED", value: 2, matches: 2 },
  { rank: 18, player: "Cody Gakpo", chineseName: "科迪·加克波", team: "荷兰", teamCode: "NED", value: 2, matches: 2 },
  { rank: 19, player: "Ayase Ueda", chineseName: "上田绮世", team: "日本", teamCode: "JPN", value: 2, matches: 2 },
  { rank: 20, player: "Daichi Kamada", chineseName: "镰田大地", team: "日本", teamCode: "JPN", value: 2, matches: 2 },
  { rank: 21, player: "Mikel Oyarzabal", chineseName: "米克尔·奥亚萨瓦尔", team: "西班牙", teamCode: "ESP", value: 2, matches: 1 },
  { rank: 22, player: "Maxi Araujo", chineseName: "马克西·阿劳霍", team: "乌拉圭", teamCode: "URU", value: 2, matches: 2 },
  { rank: 23, player: "Ismaila Sarr", chineseName: "伊斯梅拉·萨尔", team: "塞内加尔", teamCode: "SEN", value: 2, matches: 1 },
  { rank: 24, player: "Cristiano Ronaldo", chineseName: "克里斯蒂亚诺·罗纳尔多", team: "葡萄牙", teamCode: "POR", value: 2, matches: 1 },
  { rank: 25, player: "Daniel Munoz", chineseName: "丹尼尔·穆尼奥斯", team: "哥伦比亚", teamCode: "COL", value: 2, matches: 2 },
  { rank: 26, player: "Julian Quinones", chineseName: "胡利安·基尼奥内斯", team: "墨西哥", teamCode: "MEX", value: 2, matches: 3 },
  { rank: 27, player: "Ruben Vargas", chineseName: "鲁本·巴尔加斯", team: "瑞士", teamCode: "SUI", value: 2, matches: 3 },
  { rank: 28, player: "Ermin Mahmic", chineseName: "埃尔明·马赫米奇", team: "波黑", teamCode: "BIH", value: 2, matches: 3 },
  { rank: 29, player: "Nicolas Pepe", chineseName: "尼古拉·佩佩", team: "科特迪瓦", teamCode: "CIV", value: 2, matches: 1 },
  { rank: 30, player: "Anthony Elanga", chineseName: "安东尼·埃兰加", team: "瑞典", teamCode: "SWE", value: 2, matches: 2 },
  { rank: 31, player: "Pape Gueye", chineseName: "Gueye", team: "塞内加尔", teamCode: "SEN", value: 2, matches: 2 },
  { rank: 32, player: "Raul Jimenez", chineseName: "劳尔·希门尼斯", team: "墨西哥", teamCode: "MEX", value: 1, matches: 2 },
  { rank: 33, player: "Inbeom Hwang", chineseName: "黄仁范", team: "韩国", teamCode: "KOR", value: 1, matches: 2 },
  { rank: 34, player: "Hyeongyu Oh", chineseName: "吴贤揆", team: "韩国", teamCode: "KOR", value: 1, matches: 2 },
  { rank: 35, player: "Ladislav Krejci", chineseName: "拉迪斯拉夫·克雷伊奇", team: "捷克", teamCode: "CZE", value: 1, matches: 2 },
  { rank: 36, player: "Jovo Lukic", chineseName: "约沃·卢基奇", team: "波黑", teamCode: "BIH", value: 1, matches: 2 },
  { rank: 37, player: "Giovanni Reyna", chineseName: "吉奥·雷纳", team: "美国", teamCode: "USA", value: 1, matches: 2 },
  { rank: 38, player: "Alex Freeman", chineseName: "亚历克斯·弗里曼", team: "美国", teamCode: "USA", value: 1, matches: 2 },
  { rank: 39, player: "Auston Trusty", chineseName: "奥斯顿·特拉斯蒂", team: "美国", teamCode: "USA", value: 1, matches: 3 },
  { rank: 40, player: "Sebastian Berhalter", chineseName: "塞巴斯蒂安·贝哈尔特", team: "美国", teamCode: "USA", value: 1, matches: 3 },
  { rank: 41, player: "Arda Guler", chineseName: "阿尔达·居莱尔", team: "土耳其", teamCode: "TUR", value: 1, matches: 3 },
  { rank: 42, player: "Orkun Kokcu", chineseName: "奥尔昆·科克曲", team: "土耳其", teamCode: "TUR", value: 1, matches: 3 },
  { rank: 43, player: "Kaan Ayhan", chineseName: "卡安·艾汉", team: "土耳其", teamCode: "TUR", value: 1, matches: 3 },
  { rank: 44, player: "Mauricio", chineseName: "毛里西奥", team: "巴拉圭", teamCode: "PAR", value: 1, matches: 2 },
  { rank: 45, player: "Matias Galarza", chineseName: "马蒂亚斯·加拉尔萨", team: "巴拉圭", teamCode: "PAR", value: 1, matches: 2 },
  { rank: 46, player: "Boualem Khoukhi", chineseName: "布阿莱姆·胡希", team: "卡塔尔", teamCode: "QAT", value: 1, matches: 2 },
  { rank: 47, player: "John McGinn", chineseName: "约翰·麦金", team: "苏格兰", teamCode: "SCO", value: 1, matches: 2 },
  { rank: 48, player: "Nestory Irankunda", chineseName: "内斯托里·伊兰昆达", team: "澳大利亚", teamCode: "AUS", value: 1, matches: 2 },
  { rank: 49, player: "Connor Metcalfe", chineseName: "康纳·梅特卡夫", team: "澳大利亚", teamCode: "AUS", value: 1, matches: 2 },
  { rank: 50, player: "Felix Nmecha", chineseName: "费利克斯·恩梅查", team: "德国", teamCode: "GER", value: 1, matches: 2 },
  { rank: 51, player: "Livano Comenencia", chineseName: "利瓦诺·科梅嫩西亚", team: "库拉索", teamCode: "CUW", value: 1, matches: 1 },
  { rank: 52, player: "Nico Schlotterbeck", chineseName: "尼科·施洛特贝克", team: "德国", teamCode: "GER", value: 1, matches: 2 },
  { rank: 53, player: "Jamal Musiala", chineseName: "贾马尔·穆西亚拉", team: "德国", teamCode: "GER", value: 1, matches: 2 },
  { rank: 54, player: "Nathaniel Brown", chineseName: "纳撒尼尔·布朗", team: "德国", teamCode: "GER", value: 1, matches: 2 },
  { rank: 55, player: "Virgil van Dijk", chineseName: "维吉尔·范戴克", team: "荷兰", teamCode: "NED", value: 1, matches: 2 },
  { rank: 56, player: "Keito Nakamura", chineseName: "中村敬斗", team: "日本", teamCode: "JPN", value: 1, matches: 2 },
  { rank: 57, player: "Junya Ito", chineseName: "伊东纯也", team: "日本", teamCode: "JPN", value: 1, matches: 2 },
  { rank: 58, player: "Amad Diallo", chineseName: "阿马德·迪亚洛", team: "科特迪瓦", teamCode: "CIV", value: 1, matches: 2 },
  { rank: 59, player: "Alexander Isak", chineseName: "亚历山大·伊萨克", team: "瑞典", teamCode: "SWE", value: 1, matches: 2 },
  { rank: 60, player: "Omar Rekik", chineseName: "奥马尔·雷基克", team: "突尼斯", teamCode: "TUN", value: 1, matches: 2 },
  { rank: 61, player: "Viktor Gyokeres", chineseName: "维克托·约克雷斯", team: "瑞典", teamCode: "SWE", value: 1, matches: 2 },
  { rank: 62, player: "Mattias Svanberg", chineseName: "马蒂亚斯·斯万贝里", team: "瑞典", teamCode: "SWE", value: 1, matches: 2 },
  { rank: 63, player: "Emam Ashour", chineseName: "埃马姆·阿舒尔", team: "埃及", teamCode: "EGY", value: 1, matches: 1 },
  { rank: 64, player: "Abdulelah Alamri", chineseName: "阿卜杜勒拉·阿拉姆里", team: "沙特阿拉伯", teamCode: "KSA", value: 1, matches: 1 },
  { rank: 65, player: "Ramin Rezaeian", chineseName: "拉明·雷扎伊安", team: "伊朗", teamCode: "IRN", value: 1, matches: 1 },
  { rank: 66, player: "Mohammad Mohebi", chineseName: "穆罕默德·莫赫比", team: "伊朗", teamCode: "IRN", value: 1, matches: 1 },
  { rank: 67, player: "Bradley Barcola", chineseName: "布拉德利·巴尔科拉", team: "法国", teamCode: "FRA", value: 1, matches: 1 },
  { rank: 68, player: "Ousmane Dembele", chineseName: "奥斯曼·登贝莱", team: "法国", teamCode: "FRA", value: 1, matches: 1 },
  { rank: 69, player: "Ibrahim Mbaye", chineseName: "易卜拉欣·姆巴耶", team: "塞内加尔", teamCode: "SEN", value: 1, matches: 1 },
  { rank: 70, player: "Aymen Hussein", chineseName: "艾曼·侯赛因", team: "伊拉克", teamCode: "IRQ", value: 1, matches: 1 },
  { rank: 71, player: "Leo Ostigard", chineseName: "莱奥·厄斯蒂高", team: "挪威", teamCode: "NOR", value: 1, matches: 1 },
  { rank: 72, player: "Marcus Pedersen", chineseName: "马库斯·佩德森", team: "挪威", teamCode: "NOR", value: 1, matches: 1 },
  { rank: 73, player: "Romano Schmid", chineseName: "罗马诺·施密德", team: "奥地利", teamCode: "AUT", value: 1, matches: 1 },
  { rank: 74, player: "Marko Arnautovic", chineseName: "马尔科·阿瑙托维奇", team: "奥地利", teamCode: "AUT", value: 1, matches: 1 },
  { rank: 75, player: "Musa Al-Taamari", chineseName: "穆萨·阿尔塔马里", team: "约旦", teamCode: "JOR", value: 1, matches: 1 },
  { rank: 76, player: "Joao Neves", chineseName: "若昂·内维斯", team: "葡萄牙", teamCode: "POR", value: 1, matches: 1 },
  { rank: 77, player: "Nuno Mendes", chineseName: "努诺·门德斯", team: "葡萄牙", teamCode: "POR", value: 1, matches: 1 },
  { rank: 78, player: "Rafael Leao", chineseName: "拉斐尔·莱奥", team: "葡萄牙", teamCode: "POR", value: 1, matches: 1 },
  { rank: 79, player: "Ante Budimir", chineseName: "安特·布迪米尔", team: "克罗地亚", teamCode: "CRO", value: 1, matches: 1 },
  { rank: 80, player: "Yoane Wissa", chineseName: "约安·维萨", team: "刚果民主共和国", teamCode: "COD", value: 1, matches: 1 },
  { rank: 81, player: "Harry Kane", chineseName: "哈里·凯恩", team: "英格兰", teamCode: "ENG", value: 1, matches: 1 },
  { rank: 82, player: "Martin Baturina", chineseName: "马丁·巴图里纳", team: "克罗地亚", teamCode: "CRO", value: 1, matches: 1 },
  { rank: 83, player: "Petar Musa", chineseName: "佩塔尔·穆萨", team: "克罗地亚", teamCode: "CRO", value: 1, matches: 1 },
  { rank: 84, player: "Jude Bellingham", chineseName: "裘德·贝林厄姆", team: "英格兰", teamCode: "ENG", value: 1, matches: 1 },
  { rank: 85, player: "Marcus Rashford", chineseName: "马库斯·拉什福德", team: "英格兰", teamCode: "ENG", value: 1, matches: 1 },
  { rank: 86, player: "Caleb Yirenkyi", chineseName: "凯莱布·耶伦基", team: "加纳", teamCode: "GHA", value: 1, matches: 1 },
  { rank: 87, player: "Abbosbek Fayzullaev", chineseName: "阿博斯别克·法伊祖拉耶夫", team: "乌兹别克斯坦", teamCode: "UZB", value: 1, matches: 1 },
  { rank: 88, player: "Jefferson Lerma", chineseName: "杰斐逊·莱尔马", team: "哥伦比亚", teamCode: "COL", value: 1, matches: 1 },
  { rank: 89, player: "Granit Xhaka", chineseName: "格拉尼特·扎卡", team: "瑞士", teamCode: "SUI", value: 1, matches: 2 },
  { rank: 90, player: "Michal Sadilek", chineseName: "米哈尔·萨迪莱克", team: "捷克", teamCode: "CZE", value: 1, matches: 2 },
  { rank: 91, player: "Teboho Mokoena", chineseName: "特博霍·莫科纳", team: "南非", teamCode: "RSA", value: 1, matches: 2 },
  { rank: 92, player: "Nathan Saliba", chineseName: "内森·萨利巴", team: "加拿大", teamCode: "CAN", value: 1, matches: 2 },
  { rank: 93, player: "Luis Romo", chineseName: "路易斯·罗莫", team: "墨西哥", teamCode: "MEX", value: 1, matches: 2 },
  { rank: 94, player: "Breel Embolo", chineseName: "布雷尔·恩博洛", team: "瑞士", teamCode: "SUI", value: 1, matches: 3 },
  { rank: 95, player: "Mateo Chavez", chineseName: "马特奥·查韦斯", team: "墨西哥", teamCode: "MEX", value: 1, matches: 3 },
  { rank: 96, player: "Alvaro Fidalgo", chineseName: "阿尔瓦罗·菲达尔戈", team: "墨西哥", teamCode: "MEX", value: 1, matches: 3 },
  { rank: 97, player: "Thapelo Maseko", chineseName: "塔佩洛·马塞科", team: "南非", teamCode: "RSA", value: 1, matches: 3 },
  { rank: 98, player: "Leroy Sane", chineseName: "勒鲁瓦·萨内", team: "德国", teamCode: "GER", value: 1, matches: 1 },
  { rank: 99, player: "Nilson Angulo", chineseName: "尼尔松·安古洛", team: "厄瓜多尔", teamCode: "ECU", value: 1, matches: 1 },
  { rank: 100, player: "Gonzalo Plata", chineseName: "贡萨洛·普拉塔", team: "厄瓜多尔", teamCode: "ECU", value: 1, matches: 1 },
  { rank: 101, player: "Hazem Mastouri", chineseName: "哈泽姆·马斯图里", team: "突尼斯", teamCode: "TUN", value: 1, matches: 1 },
  { rank: 102, player: "Daizen Maeda", chineseName: "前田大然", team: "日本", teamCode: "JPN", value: 1, matches: 1 },
  { rank: 103, player: "Jan Paul van Hecke", chineseName: "扬-保罗·范黑克", team: "荷兰", teamCode: "NED", value: 1, matches: 1 },
  { rank: 104, player: "Franck Kessie", chineseName: "弗兰克·凯西", team: "科特迪瓦", teamCode: "CIV", value: 1, matches: 2 },
  { rank: 105, player: "Lamine Yamal", chineseName: "拉明·亚马尔", team: "西班牙", teamCode: "ESP", value: 1, matches: 1 },
  { rank: 106, player: "Kevin Pina", chineseName: "凯文·皮纳", team: "佛得角", teamCode: "CPV", value: 1, matches: 1 },
  { rank: 107, player: "Agustin Canobbio", chineseName: "阿古斯丁·卡诺比奥", team: "乌拉圭", teamCode: "URU", value: 1, matches: 1 },
  { rank: 108, player: "Helio Varela", chineseName: "赫利奥·瓦雷拉", team: "佛得角", teamCode: "CPV", value: 1, matches: 1 },
  { rank: 109, player: "Trezeguet", chineseName: "特雷泽盖", team: "埃及", teamCode: "EGY", value: 1, matches: 2 },
  { rank: 110, player: "Zizo", chineseName: "齐佐", team: "埃及", teamCode: "EGY", value: 1, matches: 2 },
  { rank: 111, player: "Mohamed Salah", chineseName: "穆罕默德·萨拉赫", team: "埃及", teamCode: "EGY", value: 1, matches: 2 },
  { rank: 112, player: "Finn Surman", chineseName: "芬恩·瑟曼", team: "新西兰", teamCode: "NZL", value: 1, matches: 2 },
  { rank: 113, player: "Nizar Alrashdan", chineseName: "尼扎尔·拉什丹", team: "约旦", teamCode: "JOR", value: 1, matches: 2 },
  { rank: 114, player: "Amine Gouiri", chineseName: "阿明·古伊里", team: "阿尔及利亚", teamCode: "ALG", value: 1, matches: 2 },
  { rank: 115, player: "Nadhir Benbouali", chineseName: "纳迪尔·本布阿里", team: "阿尔及利亚", teamCode: "ALG", value: 1, matches: 2 },
  { rank: 116, player: "Promise David", chineseName: "普罗米斯·戴维", team: "加拿大", teamCode: "CAN", value: 1, matches: 3 },
  { rank: 117, player: "Kerim Alajbegovic", chineseName: "凯里姆·阿拉伊贝戈维奇", team: "波黑", teamCode: "BIH", value: 1, matches: 3 },
  { rank: 118, player: "Hassan Alhaydos", chineseName: "哈桑·海多斯", team: "卡塔尔", teamCode: "QAT", value: 1, matches: 3 },
  { rank: 119, player: "Lenny Joseph", chineseName: "莱尼·约瑟夫", team: "海地", teamCode: "HAI", value: 1, matches: 3 },
  { rank: 120, player: "Wilson Isidor", chineseName: "威尔逊·伊西多尔", team: "海地", teamCode: "HAI", value: 1, matches: 3 },
  { rank: 121, player: "Achraf Hakimi", chineseName: "阿什拉夫·哈基米", team: "摩洛哥", teamCode: "MAR", value: 1, matches: 3 },
  { rank: 122, player: "Soufiane Rahimi", chineseName: "苏菲安·拉希米", team: "摩洛哥", teamCode: "MAR", value: 1, matches: 3 },
  { rank: 123, player: "Gessime Yassine", chineseName: "杰西姆·亚辛", team: "摩洛哥", teamCode: "MAR", value: 1, matches: 3 },
  { rank: 124, player: "Aasgaard", chineseName: "Aasgaard", team: "挪威", teamCode: "挪威", value: 1, matches: 1 },
  { rank: 125, player: "Désiré Doué", chineseName: "Doué", team: "法国", teamCode: "FRA", value: 1, matches: 1 },
  { rank: 126, player: "Habib Diarra", chineseName: "Diarra", team: "塞内加尔", teamCode: "SEN", value: 1, matches: 1 },
  { rank: 127, player: "Ismaïla Sarr", chineseName: "Sarr", team: "塞内加尔", teamCode: "SEN", value: 1, matches: 1 },
  { rank: 128, player: "Iliman Ndiaye", chineseName: "Ndiaye", team: "塞内加尔", teamCode: "SEN", value: 1, matches: 1 },
  { rank: 129, player: "Álex Baena", chineseName: "Baena", team: "西班牙", teamCode: "ESP", value: 1, matches: 1 }
  ];

export const assistsRanking: PlayerStat[] = [
  { rank: 1, player: "Michael Olise", chineseName: "迈克尔·奥利塞", team: "法国", teamCode: "FRA", value: 3, matches: 2 },
  { rank: 2, player: "Bruno Guimaraes", chineseName: "布鲁诺·吉马良斯", team: "巴西", teamCode: "BRA", value: 3, matches: 3 },
  { rank: 3, player: "Ryan Gravenberch", chineseName: "赖恩·赫拉芬贝赫", team: "荷兰", teamCode: "NED", value: 2, matches: 2 },
  { rank: 4, player: "Chris Wood", chineseName: "克里斯·伍德", team: "新西兰", teamCode: "NZL", value: 2, matches: 1 },
  { rank: 5, player: "Alexander Isak", chineseName: "亚历山大·伊萨克", team: "瑞典", teamCode: "SWE", value: 2, matches: 2 },
  { rank: 6, player: "Denzel Dumfries", chineseName: "丹泽尔·邓弗里斯", team: "荷兰", teamCode: "NED", value: 2, matches: 2 },
  { rank: 7, player: "Mohamed Salah", chineseName: "穆罕默德·萨拉赫", team: "埃及", teamCode: "EGY", value: 2, matches: 2 },
  { rank: 8, player: "Roberto Alvarado", chineseName: "罗伯托·阿尔瓦拉多", team: "墨西哥", teamCode: "MEX", value: 1, matches: 2 },
  { rank: 9, player: "Christian Pulisic", chineseName: "克里斯蒂安·普利西奇", team: "美国", teamCode: "USA", value: 1, matches: 2 },
  { rank: 10, player: "Inbeom Hwang", chineseName: "黄仁范", team: "韩国", teamCode: "KOR", value: 1, matches: 2 },
  { rank: 11, player: "Promise David", chineseName: "普罗米斯·戴维", team: "加拿大", teamCode: "CAN", value: 1, matches: 2 },
  { rank: 12, player: "Sead Kolasinac", chineseName: "塞亚德·科拉希纳茨", team: "波黑", teamCode: "BIH", value: 1, matches: 2 },
  { rank: 13, player: "Homam Ahmed", chineseName: "霍马姆·艾哈迈德", team: "卡塔尔", teamCode: "QAT", value: 1, matches: 2 },
  { rank: 14, player: "Brahim Diaz", chineseName: "卜拉欣·迪亚斯", team: "摩洛哥", teamCode: "MAR", value: 1, matches: 2 },
  { rank: 15, player: "Paul Okon-Engstler", chineseName: "保罗·奥孔-恩斯特勒", team: "澳大利亚", teamCode: "AUS", value: 1, matches: 2 },
  { rank: 16, player: "Viktor Gyokeres", chineseName: "维克托·约克雷斯", team: "瑞典", teamCode: "SWE", value: 1, matches: 2 },
  { rank: 17, player: "Hannibal Mejbri", chineseName: "汉尼拔·梅布里", team: "突尼斯", teamCode: "TUN", value: 1, matches: 1 },
  { rank: 18, player: "Saman Ghoddos", chineseName: "萨曼·古多斯", team: "伊朗", teamCode: "IRN", value: 1, matches: 1 },
  { rank: 19, player: "Adrien Rabiot", chineseName: "阿德里安·拉比奥", team: "法国", teamCode: "FRA", value: 1, matches: 1 },
  { rank: 20, player: "David Moller Wolfe", chineseName: "大卫·默勒·沃尔夫", team: "挪威", teamCode: "NOR", value: 1, matches: 1 },
  { rank: 21, player: "Martin Odegaard", chineseName: "马丁·厄德高", team: "挪威", teamCode: "NOR", value: 1, matches: 2 },
  { rank: 22, player: "Amir Al-Ammari", chineseName: "阿米尔·阿拉马里", team: "伊拉克", teamCode: "IRQ", value: 1, matches: 1 },
  { rank: 23, player: "Pedro Neto", chineseName: "佩德罗·内托", team: "葡萄牙", teamCode: "POR", value: 1, matches: 1 },
  { rank: 24, player: "Arthur Masuaku", chineseName: "阿图尔·马苏亚库", team: "刚果民主共和国", teamCode: "COD", value: 1, matches: 1 },
  { rank: 25, player: "Declan Rice", chineseName: "德克兰·赖斯", team: "英格兰", teamCode: "ENG", value: 1, matches: 1 },
  { rank: 26, player: "Petar Sucic", chineseName: "彼得·苏契奇", team: "克罗地亚", teamCode: "CRO", value: 1, matches: 1 },
  { rank: 27, player: "Ivan Perisic", chineseName: "伊万·佩里希奇", team: "克罗地亚", teamCode: "CRO", value: 1, matches: 1 },
  { rank: 28, player: "Elliot Anderson", chineseName: "埃利奥特·安德森", team: "英格兰", teamCode: "ENG", value: 1, matches: 1 },
  { rank: 29, player: "Bukayo Saka", chineseName: "布卡约·萨卡", team: "英格兰", teamCode: "ENG", value: 1, matches: 1 },
  { rank: 30, player: "Brandon Thomas-Asante", chineseName: "布兰登·托马斯-阿桑特", team: "加纳", teamCode: "GHA", value: 1, matches: 1 },
  { rank: 31, player: "Luis Diaz", chineseName: "路易斯·迪亚斯", team: "哥伦比亚", teamCode: "COL", value: 1, matches: 1 },
  { rank: 32, player: "Cody Gakpo", chineseName: "科迪·加克波", team: "荷兰", teamCode: "NED", value: 1, matches: 2 },
  { rank: 33, player: "Crysencio Summerville", chineseName: "克里森西奥·萨默维尔", team: "荷兰", teamCode: "NED", value: 1, matches: 2 },
  { rank: 34, player: "Memphis Depay", chineseName: "孟菲斯·德佩", team: "荷兰", teamCode: "NED", value: 1, matches: 2 },
  { rank: 35, player: "Nadiem Amiri", chineseName: "纳迪姆·阿米里", team: "德国", teamCode: "GER", value: 1, matches: 2 },
  { rank: 36, player: "Felix Nmecha", chineseName: "费利克斯·恩梅查", team: "德国", teamCode: "GER", value: 1, matches: 2 },
  { rank: 37, player: "Kaishu Sano", chineseName: "佐野海舟", team: "日本", teamCode: "JPN", value: 1, matches: 2 },
  { rank: 38, player: "Ayase Ueda", chineseName: "上田绮世", team: "日本", teamCode: "JPN", value: 1, matches: 2 },
  { rank: 39, player: "Keito Nakamura", chineseName: "中村敬斗", team: "日本", teamCode: "JPN", value: 1, matches: 2 },
  { rank: 40, player: "Mohamed Hany", chineseName: "穆罕默德·哈尼", team: "埃及", teamCode: "EGY", value: 1, matches: 2 },
  { rank: 41, player: "Joao Cancelo", chineseName: "若昂·坎塞洛", team: "葡萄牙", teamCode: "POR", value: 1, matches: 1 },
  { rank: 42, player: "Bruno Fernandes", chineseName: "布鲁诺·费尔南德斯", team: "葡萄牙", teamCode: "POR", value: 1, matches: 1 },
  { rank: 43, player: "Cristiano Ronaldo", chineseName: "克里斯蒂亚诺·罗纳尔多", team: "葡萄牙", teamCode: "POR", value: 1, matches: 1 },
  { rank: 44, player: "Josip Stanisic", chineseName: "约西普·斯塔尼希奇", team: "克罗地亚", teamCode: "CRO", value: 1, matches: 1 },
  { rank: 45, player: "Johan Manzambi", chineseName: "约翰·曼赞比", team: "瑞士", teamCode: "SUI", value: 1, matches: 3 },
  { rank: 46, player: "Breel Embolo", chineseName: "布雷尔·恩博洛", team: "瑞士", teamCode: "SUI", value: 1, matches: 3 },
  { rank: 47, player: "Nathan Saliba", chineseName: "内森·萨利巴", team: "加拿大", teamCode: "CAN", value: 1, matches: 3 },
  { rank: 48, player: "Achraf Hakimi", chineseName: "阿什拉夫·哈基米", team: "摩洛哥", teamCode: "MAR", value: 1, matches: 3 },
  { rank: 49, player: "Soufiane Rahimi", chineseName: "苏菲安·拉希米", team: "摩洛哥", teamCode: "MAR", value: 1, matches: 3 },
  { rank: 50, player: "Yan Diomande", chineseName: "扬·迪奥曼德", team: "科特迪瓦", teamCode: "CIV", value: 1, matches: 1 },
  { rank: 51, player: "Ibrahim Sangare", chineseName: "易卜拉欣·桑加雷", team: "科特迪瓦", teamCode: "CIV", value: 1, matches: 1 },
  { rank: 52, player: "Virgil van Dijk", chineseName: "维吉尔·范戴克", team: "荷兰", teamCode: "NED", value: 1, matches: 2 },
  { rank: 53, player: "Tijjani Reijnders", chineseName: "蒂贾尼·赖因德斯", team: "荷兰", teamCode: "NED", value: 1, matches: 1 },
  { rank: 54, player: "Ritsu Doan", chineseName: "堂安律", team: "日本", teamCode: "JPN", value: 1, matches: 1 },
  { rank: 55, player: "Kevin Rodriguez", chineseName: "凯文·罗德里格斯", team: "厄瓜多尔", teamCode: "ECU", value: 1, matches: 1 }
  ];

export const statsNotice = {
    title: "乌拉圭 0-1 西班牙",
    body: "比赛已完成，进球榜和助攻榜已更新。"
  };
