services:
  fifa26:
    container_name: fifa26
    build: .
    environment:
      VISIT_STATS_FILE: /data/visit-stats.json
    volumes:
      - ./data:/data
    expose:
      - "3000"
    networks:
      - npm-network
    restart: unless-stopped

networks:
  npm-network:
    external: true
